# Generated by Django 2.1.5 on 2022-06-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
