# Generated by Django 2.1.5 on 2022-07-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_reactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='reactions',
            name='Lit_ref',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='additional_products',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='cas_member_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='catalyst',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='conditions',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='endo_exo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='pressure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='products',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='reactants',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='reagents',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='solvents',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='stages',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='temp',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='time',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reactions',
            name='yield_percent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='reaction_desc',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='reaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
