# Generated by Django 2.1.5 on 2022-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220719_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactions',
            options={'verbose_name_plural': 'Reactions'},
        ),
    ]
