# Generated by Django 2.1.5 on 2022-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220719_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
