# Generated by Django 2.1.5 on 2022-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_delete_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_id', models.IntegerField(null=True)),
                ('reaction_desc', models.CharField(max_length=1024, null=True)),
                ('reactants', models.CharField(max_length=1024, null=True)),
                ('products', models.CharField(max_length=1024, null=True)),
                ('yield_percent', models.CharField(max_length=20, null=True)),
                ('additional_products', models.CharField(max_length=1024, null=True)),
                ('steps', models.IntegerField(null=True)),
                ('stages', models.CharField(max_length=1024, null=True)),
                ('reagents', models.CharField(max_length=1024, null=True)),
                ('catalyst', models.CharField(max_length=1024, null=True)),
                ('solvents', models.CharField(max_length=1024, null=True)),
                ('conditions', models.CharField(max_length=1024, null=True)),
                ('time', models.CharField(max_length=1024, null=True)),
                ('temp', models.CharField(max_length=1024, null=True)),
                ('pressure', models.CharField(max_length=20, null=True)),
                ('Lit_ref', models.CharField(max_length=2048, null=True)),
                ('endo_exo', models.CharField(max_length=20, null=True)),
                ('cas_member_method', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reactions',
            },
        ),
    ]
